// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter/greeter.proto

package com.example.grpc.pb.greeter;

/**
 * Protobuf type {@code DataStruct}
 */
public final class DataStruct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DataStruct)
    DataStructOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataStruct.newBuilder() to construct.
  private DataStruct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataStruct() {
    message_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataStruct();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.pb.greeter.GreeterOuterClass.internal_static_DataStruct_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.pb.greeter.GreeterOuterClass.internal_static_DataStruct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.pb.greeter.DataStruct.class, com.example.grpc.pb.greeter.DataStruct.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList message_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string message = 1;</code>
   * @return A list containing the message.
   */
  public com.google.protobuf.ProtocolStringList
      getMessageList() {
    return message_;
  }
  /**
   * <code>repeated string message = 1;</code>
   * @return The count of message.
   */
  public int getMessageCount() {
    return message_.size();
  }
  /**
   * <code>repeated string message = 1;</code>
   * @param index The index of the element to return.
   * @return The message at the given index.
   */
  public java.lang.String getMessage(int index) {
    return message_.get(index);
  }
  /**
   * <code>repeated string message = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the message at the given index.
   */
  public com.google.protobuf.ByteString
      getMessageBytes(int index) {
    return message_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < message_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < message_.size(); i++) {
        dataSize += computeStringSizeNoTag(message_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMessageList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.pb.greeter.DataStruct)) {
      return super.equals(obj);
    }
    com.example.grpc.pb.greeter.DataStruct other = (com.example.grpc.pb.greeter.DataStruct) obj;

    if (!getMessageList()
        .equals(other.getMessageList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessageCount() > 0) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.pb.greeter.DataStruct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.pb.greeter.DataStruct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.pb.greeter.DataStruct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.pb.greeter.DataStruct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DataStruct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DataStruct)
      com.example.grpc.pb.greeter.DataStructOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.pb.greeter.GreeterOuterClass.internal_static_DataStruct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.pb.greeter.GreeterOuterClass.internal_static_DataStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.pb.greeter.DataStruct.class, com.example.grpc.pb.greeter.DataStruct.Builder.class);
    }

    // Construct using com.example.grpc.pb.greeter.DataStruct.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.pb.greeter.GreeterOuterClass.internal_static_DataStruct_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.pb.greeter.DataStruct getDefaultInstanceForType() {
      return com.example.grpc.pb.greeter.DataStruct.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.pb.greeter.DataStruct build() {
      com.example.grpc.pb.greeter.DataStruct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.pb.greeter.DataStruct buildPartial() {
      com.example.grpc.pb.greeter.DataStruct result = new com.example.grpc.pb.greeter.DataStruct(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.pb.greeter.DataStruct result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        message_.makeImmutable();
        result.message_ = message_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.pb.greeter.DataStruct) {
        return mergeFrom((com.example.grpc.pb.greeter.DataStruct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.pb.greeter.DataStruct other) {
      if (other == com.example.grpc.pb.greeter.DataStruct.getDefaultInstance()) return this;
      if (!other.message_.isEmpty()) {
        if (message_.isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
        } else {
          ensureMessageIsMutable();
          message_.addAll(other.message_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureMessageIsMutable();
              message_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList message_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMessageIsMutable() {
      if (!message_.isModifiable()) {
        message_ = new com.google.protobuf.LazyStringArrayList(message_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string message = 1;</code>
     * @return A list containing the message.
     */
    public com.google.protobuf.ProtocolStringList
        getMessageList() {
      message_.makeImmutable();
      return message_;
    }
    /**
     * <code>repeated string message = 1;</code>
     * @return The count of message.
     */
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <code>repeated string message = 1;</code>
     * @param index The index of the element to return.
     * @return The message at the given index.
     */
    public java.lang.String getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <code>repeated string message = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the message at the given index.
     */
    public com.google.protobuf.ByteString
        getMessageBytes(int index) {
      return message_.getByteString(index);
    }
    /**
     * <code>repeated string message = 1;</code>
     * @param index The index to set the value at.
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMessageIsMutable();
      message_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message = 1;</code>
     * @param value The message to add.
     * @return This builder for chaining.
     */
    public Builder addMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMessageIsMutable();
      message_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message = 1;</code>
     * @param values The message to add.
     * @return This builder for chaining.
     */
    public Builder addAllMessage(
        java.lang.Iterable<java.lang.String> values) {
      ensureMessageIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, message_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message = 1;</code>
     * @param value The bytes of the message to add.
     * @return This builder for chaining.
     */
    public Builder addMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMessageIsMutable();
      message_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DataStruct)
  }

  // @@protoc_insertion_point(class_scope:DataStruct)
  private static final com.example.grpc.pb.greeter.DataStruct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.pb.greeter.DataStruct();
  }

  public static com.example.grpc.pb.greeter.DataStruct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataStruct>
      PARSER = new com.google.protobuf.AbstractParser<DataStruct>() {
    @java.lang.Override
    public DataStruct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataStruct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataStruct> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.pb.greeter.DataStruct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

