// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter/greeter.proto

package com.example.grpc.pb.greeter;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .DataStruct data = 2;</code>
   */
  java.util.List<com.example.grpc.pb.greeter.DataStruct> 
      getDataList();
  /**
   * <code>repeated .DataStruct data = 2;</code>
   */
  com.example.grpc.pb.greeter.DataStruct getData(int index);
  /**
   * <code>repeated .DataStruct data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .DataStruct data = 2;</code>
   */
  java.util.List<? extends com.example.grpc.pb.greeter.DataStructOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .DataStruct data = 2;</code>
   */
  com.example.grpc.pb.greeter.DataStructOrBuilder getDataOrBuilder(
      int index);
}
